### ISSUE TITLE
crypto.Credentials is deprecated. Use tls.SecureContext instead.

### ISSUE THREAD

**Issue by jmls** [motss/scryptify#18]
### Description
I get this deprecation notice when running the sample

### Expected outcome
not to get the notice ;)

### Actual outcome
(node:22838) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:22838) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
### Steps to reproduce
run the sample
### Versions of affected system

- **scryptify 0.2.1**:
- **Node.js v9.3.0**:
- **NPM 5.5.1**:
- **Platform details** linux, ubuntu 17.10

**Comment by jmls** [comment]
afraid not. I installed 9.4.0, removed node_modules and reinstalled

```
nodeable@8e17db6691f8:/data/rtb-dashboard$ node -v
v9.4.0
nodeable@8e17db6691f8:/data/rtb-dashboard$ node test/secret
(node:1863) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:1863) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
xxx 3fbbd532bbaaae953d2a091c85c8ef57:92d40934b05e888f3e355c9b874ce1d9
nodeable@8e17db6691f8:/data/rtb-dashboard$ 

```

**Comment by motss** [comment]
@jmls Managed to find the root cause of this. Hope the fix will get rid of the deprecation warning. 🤔
